### ISSUE TITLE
Cannot set doc-related preferences for group.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs-in-group#5]
Something about `BPDIG_Group_Extension` extending `BP_Docs_Group_Extension` causes the `create` and `edit` screen methods to be ignored, resulting in no way to update the docs preferences for a group.

**Comment by StrothiP** [comment]
Dear @boonebgorges,

not sure if this is the same issue that @dcavins is referring to, but the entire section around Access and Group Folders goes missing when the plugin is activated?! I tested it in my test environment with Twenty Nineteen and the issue remains. The associated groups screen also disappeared, but that makes sense. But Folders and Access should remain accessible?! 

Would be great if you could look into what might be causing the issue.

Thanks so much in advance,

Kind regards, Philip

**Comment by boonebgorges** [comment]
Yup, sounds like this is the same issue as what's reported by @dcavins.

I identified the issue and just pushed up a fix. This will be included in a tagged release, likely the next time Commons In A Box sees a release.
